CREATE TABLE [OfflocStaging].[Lookups.Nationality](
	[Nationality] [nvarchar](50) NOT NULL,
	[EEA] [bit] NOT NULL,
 CONSTRAINT [PK_Lookups.Nationality] PRIMARY KEY CLUSTERED 
(
	[Nationality] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]