CREATE TABLE [DeliusStaging].[Merging.NINOValidPrefixes](
	[Prefix] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Merging.NINOValidPrefixes] PRIMARY KEY CLUSTERED 
(
	[Prefix] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]