CREATE TABLE [OfflocRunningPicture].[OffenderStatus]
(
	[NOMSnumber] NVARCHAR(7) NOT NULL,
	CONSTRAINT [PK_OffenderStatus] PRIMARY KEY (NOMSnumber),
	[CustodyStatus] NVARCHAR(20) NULL,
	[InmateStatus] NVARCHAR(50) NULL,
	[IsActive] BIT NOT NULL,
	[ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
) ON [PRIMARY] WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [OfflocTemporal].[OffenderStatus]))
