CREATE TABLE [OfflocRunningPicture].[VeteranFlagLog]
(
	[NomisNumber] CHAR(7),
	[IsActive] BIT NOT NULL,
	CONSTRAINT [PK_VeteranFlagLog] PRIMARY KEY (NomisNumber) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON),
	[ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
) ON [PRIMARY] WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [OfflocTemporal].[VeteranFlagLog]))
