global using Amazon.S3;
global using EnvironmentSetup;
global using FileSync;
global using Messaging.Interfaces;
global using Messaging.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Serilog;