CREATE PROCEDURE [OfflocStaging].[InitializeStandardisationLookups]
AS

	Declare @RowCount as int = 0;
	
	--Populate [Lookups.Ethnicity] table
	SELECT 
		@RowCount = COUNT(1) 
	FROM 
		[OfflocStaging].[Lookups.Ethnicity];

	IF @RowCount = 0
	BEGIN
		INSERT INTO 
			[OfflocStagingDb].[OfflocStaging].[Lookups.Ethnicity] 
		VALUES
			(1, '', 15),
			(2, '', 15),
			(3, 'Arab', 12),
			(4, 'Asian or Asian British: Bangladeshi', 1),
			(5, 'Asian or Asian British: Chinese', 13),
			(6, 'Asian or Asian British: Indian', 2),
			(7, 'Asian or Asian British: Other', 3),
			(8, 'Asian or Asian British: Pakistani', 4),
			(9, 'Asian/Asian British: Any other backgr''nd', 3),
			(10, 'Asian/Asian British: Bangladeshi', 1),
			(11, 'Asian/Asian British: Chinese', 13),
			(12, 'Asian/Asian British: Indian', 2),
			(13, 'Asian/Asian British: Pakistani', 4),
			(14, 'Black or Black British: African', 5),
			(15, 'Black or Black British: Caribbean', 6),
			(16, 'Black or Black British: Other', 7),
			(17, 'Black/Black British: African', 5),
			(18, 'Black/Black British: Any other Backgr''nd', 7),
			(19, 'Black/Black British: Caribbean', 6),
			(20, 'Chinese', 13),
			(21, 'Mixed : Other', 8),
			(22, 'Mixed: Any other background', 8),
			(23, 'Mixed: White and Asian', 9),
			(24, 'Mixed: White and Black African', 10),
			(25, 'Mixed: White and Black Caribbean', 11),
			(26, 'Needs to be confirmed following Merge', 15),
			(27, 'Other Ethnic Group', 14),
			(28, 'Other: Any other background', 14),
			(29, 'Other: Arab', 12),
			(30, 'Prefer not to say', 15),
			(31, 'Refusal', 15),
			(32, 'White : Irish', 18),
			(33, 'White : Irish Traveller/Gypsy', 17),
			(34, 'White : Other', 19),
			(35, 'White: Any other background', 19),
			(36, 'White: British/English/Welsh/Scottish/Northern Irish', 16),
			(37, 'White: Eng./Welsh/Scot./N.Irish/British', 16),
			(38, 'White: Gypsy or Irish Traveller', 17),
			(39, 'Z_Dummy Ethnicity 04', 15),
			(40, 'Z_Dummy Ethnicity 05', 15),
			(41, 'Other (historic)', 14),
			(42, 'Black-African', 5),
			(43, 'White-British', 16),
			(44, 'White Background', 19),
			(45, 'Mixed Black African and White', 10),
			(46, 'Black African', 5),
			(47, 'Missing (IAPS)', 15),
			(48, 'White: Irish', 18),
			(49, 'Mixed: Other', 8),
			(50, 'White: Gypsy, Irish Traveller, Romany', 17),
			(51, 'Other: Other', 14),
			(52, 'White: Roma', 19)
	END

	--Populate [Lookups.EthnicityStandard] table
	SELECT 
		@RowCount = COUNT(1) 
	FROM 
		[OfflocStaging].[Lookups.EthnicityStandard];

	IF @RowCount = 0
	BEGIN
		INSERT INTO 
			[OfflocStagingDb].[OfflocStaging].[Lookups.EthnicityStandard] 
		VALUES
			(1, 'Asian or Asian British: Bangladeshi', 'Asian'),
			(2, 'Asian or Asian British: Indian', 'Asian'),
			(3, 'Asian or Asian British: Other', 'Asian'),
			(4, 'Asian or Asian British: Pakistani', 'Asian'),
			(5, 'Black or Black British: African', 'Black'),
			(6, 'Black or Black British: Caribbean', 'Black'),
			(7, 'Black or Black British: Other', 'Black'),
			(8, 'Mixed: Other', 'Mixed'),
			(9, 'Mixed: White and Asian', 'Mixed'),
			(10, 'Mixed: White and Black African', 'Mixed'),
			(11, 'Mixed: White and Black Caribbean', 'Mixed'),
			(12, 'Other: Arab', 'Other'),
			(13, 'Other: Chinese', 'Other'),
			(14, 'Other: Other', 'Other'),
			(15, 'Refused / Not Stated', 'Refused / Not Stated'),
			(16, 'White: British/English/Welsh/Scottish/Northern Irish', 'White: British'),
			(17, 'White: Gypsy or Irish Traveller', 'White: Irish/Gypsy/Traveller/Other'),
			(18, 'White: Irish', 'White: Irish/Gypsy/Traveller/Other'),
			(19, 'White: Other', 'White: Irish/Gypsy/Traveller/Other')
	END

	--Populate [Lookups.Nationality] table
	SELECT 
		@RowCount = COUNT(1) 
	FROM 
		[OfflocStaging].[Lookups.Nationality];

	IF @RowCount = 0
	BEGIN
		INSERT INTO 
			[OfflocStagingDb].[OfflocStaging].[Lookups.Nationality] 
		VALUES
			('Afghan', 0),
			('Albanian', 0),
			('Algerian', 0),
			('American', 0),
			('American Samoan', 0),
			('Andorran', 1),
			('Angolan', 0),
			('Anguillan', 1),
			('Antiguan, Barbudan', 0),
			('Argentine', 0),
			('Armenian', 0),
			('Aruban', 0),
			('Australian', 0),
			('Austrian', 1),
			('Azerbaijani', 0),
			('Bahamian', 0),
			('Bahraini', 0),
			('Bangladeshi', 0),
			('Barbadian or Bajuns', 0),
			('Basotho', 0),
			('Belarusian', 0),
			('Belgian', 1),
			('Belizean', 0),
			('Beninese', 0),
			('Bermudian', 1),
			('Bhutanese', 0),
			('Bolivian', 0),
			('Bosnian, Herzegovinian', 0),
			('Brazilian', 0),
			('British', 1),
			('Bruneian', 0),
			('Bulgarian', 1),
			('Burkinabe', 0),
			('Burmese', 0),
			('Burundian', 0),
			('Cambodian', 0),
			('Cameroonian', 0),
			('Canadian', 0),
			('Cape Verdian', 0),
			('Caymanian', 1),
			('Central African', 0),
			('Chadian', 0),
			('Chilean', 0),
			('Chinese', 0),
			('Christmas Island', 0),
			('Cocos Islander', 0),
			('Colombian', 0),
			('Comoran', 0),
			('Congolese', 0),
			('Congolese (Congo, Democratic Republic)', 0),
			('Congolese (Congo, Republic of)', 0),
			('Cook Islander', 0),
			('Costa Rican', 0),
			('Croat', 1),
			('Cuban', 0),
			('Cypriot', 1),
			('Czech', 1),
			('Danish', 1),
			('Djibouti', 0),
			('Dominican', 0),
			('Dutch', 1),
			('Dutch Antillean', 0),
			('East Timorese', 0),
			('Ecuadorian', 0),
			('Egyptian', 0),
			('Emirian', 0),
			('Equatoguinean', 0),
			('Eritrean', 0),
			('Estonian', 1),
			('Ethiopian', 0),
			('Faroese', 1),
			('Fijian', 0),
			('Filipino', 0),
			('Finnish', 1),
			('French', 1),
			('French Guyanese', 0),
			('French Polynesian', 0),
			('Gabonese', 0),
			('Gambian', 0),
			('Georgian', 0),
			('German', 1),
			('Ghanaian', 0),
			('Gibraltar', 1),
			('Greek', 1),
			('Greenlandic', 0),
			('Grenadian', 0),
			('Guadeloupe', 0),
			('Guamanian', 0),
			('Guatemalan', 0),
			('Guinean', 0),
			('Guyanese', 0),
			('Haitian', 0),
			('Honduran', 0),
			('Hong Kongers', 0),
			('Hungarian', 1),
			('Icelandic', 1),
			('I-Kiribati', 0),
			('Indian', 0),
			('Indonesian', 0),
			('Iranian', 0),
			('Iraqi', 0),
			('Irish', 1),
			('Israeli', 0),
			('Italian', 1),
			('Ivorian', 0),
			('Jamaican', 0),
			('Japanese', 0),
			('Jordanian', 0),
			('Kazakhstani', 0),
			('Kenyan', 0),
			('Kittitian or Nevisian', 0),
			('Kosovan', 0),
			('Kuwaiti', 0),
			('Kyrgyzstani', 0),
			('Laotian', 0),
			('Latvian', 1),
			('Lebanese', 0),
			('Liberian', 0),
			('Libyan', 0),
			('Liechtensteiner', 1),
			('Lithuanian', 1),
			('Luxembourger', 1),
			('Macedonian', 0),
			('Mahoran', 0),
			('Malagasy', 0),
			('Malawian', 0),
			('Malaysian', 0),
			('Maldivian', 0),
			('Malian', 0),
			('Maltese', 1),
			('Marshallese', 0),
			('Martiniquais', 0),
			('Mauritanian', 0),
			('Mauritian', 0),
			('Mexican', 0),
			('Micronesian', 0),
			('Moldovan', 0),
			('Monacan', 0),
			('Mongolian', 0),
			('Montenegrin', 0),
			('Montserratian', 1),
			('Moroccan', 0),
			('Motswana', 0),
			('Mozambican', 0),
			('Namibian', 0),
			('Nauruan', 0),
			('Nepalese', 0),
			('New Caledonian', 1),
			('New Zealander', 0),
			('Nicaraguan', 0),
			('Nigerian', 0),
			('Nigerien', 0),
			('Ni-Vanuata', 0),
			('Norfolk Islander', 0),
			('North Korean', 0),
			('Norwegian', 1),
			('Omani', 0),
			('Other', 0),
			('Pakistani', 0),
			('Palauan', 0),
			('Palestinian', 0),
			('Panamanian', 0),
			('Papua New Guinean', 0),
			('Paraguayan', 0),
			('Peruvian', 0),
			('Pitcairn Islander', 1),
			('Polish', 1),
			('Portuguese', 1),
			('Puerto Rican', 0),
			('Qatari', 0),
			('Refused', 0),
			('Reunionese', 1),
			('Romanian', 1),
			('Russian', 0),
			('Rwandan', 0),
			('Sahrawi', 0),
			('Saint Helenian', 0),
			('Saint Lucian', 0),
			('Salvadoran', 0),
			('Samoan', 0),
			('San Marinese', 0),
			('Sao Tomean', 0),
			('Saudi Arabian', 0),
			('Senegalese', 0),
			('Serb', 0),
			('Serb or Croat', 0),
			('Seychellois', 0),
			('Sierra Leonean', 0),
			('Singaporean', 0),
			('Slovak', 1),
			('Slovene', 1),
			('Solomon Islander', 0),
			('Somalian', 0),
			('South African', 0),
			('South Korean', 0),
			('Spaniard', 1),
			('Sri Lankan', 0),
			('Stateless', 0),
			('Sudanese', 0),
			('Surinamer', 0),
			('Swazi', 0),
			('Swede', 1),
			('Swiss', 1),
			('Syrian', 0),
			('Taiwanese', 0),
			('Tajikistani', 0),
			('Tanzanian', 0),
			('Thai', 0),
			('Togolese', 0),
			('Tongan', 0),
			('Trinidadian, Tobagonian', 0),
			('Tunisian', 0),
			('Turk', 0),
			('Turkmen', 0),
			('Tuvaluan', 1),
			('Ugandan', 0),
			('Ukrainian', 0),
			('Unknown', 0),
			('Uruguayan', 0),
			('Uzbekistani', 0),
			('Venezuelan', 0),
			('Vietnamese', 0),
			('Vincentian', 0),
			('Virgin Islander', 1),
			('Yemenite', 0),
			('Zambian', 0),
			('Zimbabwean', 0)
	END