CREATE TABLE [Matching].[Blocks](
	[BlockId] [INT] IDENTITY(1,1) NOT NULL,
	[SourceKey] [NVARCHAR](35) NOT NULL,
	[SourceName] [NVARCHAR](16) NOT NULL,
	[TargetKey] [NVARCHAR](35) NOT NULL,
	[TargetName] [NVARCHAR](16) NOT NULL,
 CONSTRAINT [PK_Blocks] PRIMARY KEY CLUSTERED 
(
	[BlockId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO