CREATE TABLE [OfflocRunningPicture].[Identifiers]
(
	[NOMSnumber] NVARCHAR(7) NOT NULL,
	[CROno] NVARCHAR(35) NOT NULL,
	CONSTRAINT [PK_Identifiers] PRIMARY KEY (NOMSnumber),
	[IsActive] BIT NOT NULL,
	[ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)ON [PRIMARY] WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [OfflocTemporal].[Identifiers]))
